In [1]:
import pandas as pd
import altair as alt
import datapane as dp

dataset = pd.read_csv('https://covid.ourworldindata.org/data/owid-covid-data.csv')

In [4]:
dataset.location.unique()

array(['Aruba', 'Afghanistan', 'Angola', 'Anguilla', 'Albania', 'Andorra',
       'United Arab Emirates', 'Argentina', 'Armenia',
       'Antigua and Barbuda', 'Australia', 'Austria', 'Azerbaijan',
       'Burundi', 'Belgium', 'Benin', 'Bonaire Sint Eustatius and Saba',
       'Burkina Faso', 'Bangladesh', 'Bulgaria', 'Bahrain', 'Bahamas',
       'Bosnia and Herzegovina', 'Belarus', 'Belize', 'Bermuda',
       'Bolivia', 'Brazil', 'Barbados', 'Brunei', 'Bhutan', 'Botswana',
       'Central African Republic', 'Canada', 'Switzerland', 'Chile',
       'China', "Cote d'Ivoire", 'Cameroon',
       'Democratic Republic of Congo', 'Congo', 'Colombia', 'Comoros',
       'Cape Verde', 'Costa Rica', 'Cuba', 'Curacao', 'Cayman Islands',
       'Cyprus', 'Czech Republic', 'Germany', 'Djibouti', 'Dominica',
       'Denmark', 'Dominican Republic', 'Algeria', 'Ecuador', 'Egypt',
       'Eritrea', 'Western Sahara', 'Spain', 'Estonia', 'Ethiopia',
       'Finland', 'Fiji', 'Falkland Islands', 'France', 'Faeroe Islands',
       'Gabon', 'United Kingdom', 'Georgia', 'Guernsey', 'Ghana',
       'Gibraltar', 'Guinea', 'Gambia', 'Guinea-Bissau',
       'Equatorial Guinea', 'Greece', 'Grenada', 'Greenland', 'Guatemala',
       'Guam', 'Guyana', 'Hong Kong', 'Honduras', 'Croatia', 'Haiti',
       'Hungary', 'Indonesia', 'Isle of Man', 'India', 'Ireland', 'Iran',
       'Iraq', 'Iceland', 'Israel', 'Italy', 'Jamaica', 'Jersey',
       'Jordan', 'Japan', 'Kazakhstan', 'Kenya', 'Kyrgyzstan', 'Cambodia',
       'Saint Kitts and Nevis', 'South Korea', 'Kuwait', 'Laos',
       'Lebanon', 'Liberia', 'Libya', 'Saint Lucia', 'Liechtenstein',
       'Sri Lanka', 'Lesotho', 'Lithuania', 'Luxembourg', 'Latvia',
       'Morocco', 'Monaco', 'Moldova', 'Madagascar', 'Maldives', 'Mexico',
       'Macedonia', 'Mali', 'Malta', 'Myanmar', 'Montenegro', 'Mongolia',
       'Northern Mariana Islands', 'Mozambique', 'Mauritania',
       'Montserrat', 'Mauritius', 'Malawi', 'Malaysia', 'Namibia',
       'New Caledonia', 'Niger', 'Nigeria', 'Nicaragua', 'Netherlands',
       'Norway', 'Nepal', 'New Zealand', 'Oman', 'Pakistan', 'Panama',
       'Peru', 'Philippines', 'Papua New Guinea', 'Poland', 'Puerto Rico',
       'Portugal', 'Paraguay', 'Palestine', 'French Polynesia', 'Qatar',
       'Romania', 'Russia', 'Rwanda', 'Saudi Arabia', 'Sudan', 'Senegal',
       'Singapore', 'Sierra Leone', 'El Salvador', 'San Marino',
       'Somalia', 'Serbia', 'South Sudan', 'Sao Tome and Principe',
       'Suriname', 'Slovakia', 'Slovenia', 'Sweden', 'Swaziland',
       'Sint Maarten (Dutch part)', 'Seychelles', 'Syria',
       'Turks and Caicos Islands', 'Chad', 'Togo', 'Thailand',
       'Tajikistan', 'Timor', 'Trinidad and Tobago', 'Tunisia', 'Turkey',
       'Taiwan', 'Tanzania', 'Uganda', 'Ukraine', 'Uruguay',
       'United States', 'Uzbekistan', 'Vatican',
       'Saint Vincent and the Grenadines', 'Venezuela',
       'British Virgin Islands', 'United States Virgin Islands',
       'Vietnam', 'Kosovo', 'Yemen', 'South Africa', 'Zambia', 'Zimbabwe',
       'World', 'International'], dtype=object)

In [74]:
# Choose your countries from above! 
countries = ['Brazil', 'New Zealand', 'Iran']
df = dataset[dataset.location.isin(countries)]

In [34]:
dataset.columns

Index(['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases',
       'new_cases_smoothed', 'total_deaths', 'new_deaths',
       'new_deaths_smoothed', 'total_cases_per_million',
       'new_cases_per_million', 'new_cases_smoothed_per_million',
       'total_deaths_per_million', 'new_deaths_per_million',
       'new_deaths_smoothed_per_million', 'new_tests', 'total_tests',
       'total_tests_per_thousand', 'new_tests_per_thousand',
       'new_tests_smoothed', 'new_tests_smoothed_per_thousand',
       'tests_per_case', 'positive_rate', 'tests_units', 'stringency_index',
       'population', 'population_density', 'median_age', 'aged_65_older',
       'aged_70_older', 'gdp_per_capita', 'extreme_poverty',
       'cardiovasc_death_rate', 'diabetes_prevalence', 'female_smokers',
       'male_smokers', 'handwashing_facilities', 'hospital_beds_per_thousand',
       'life_expectancy', 'human_development_index'],
      dtype='object')

In [88]:
base = alt.Chart(df).encode(x='date:T', color='location').mark_area(opacity=0.5, stroke='black').interactive().properties(width='container')
c1 = base.encode(y='new_cases_smoothed_per_million')
c2 = base.encode(y='new_deaths_smoothed_per_million')

In [86]:
c3 = base.encode(y='total_deaths_per_million:Q').properties(width='container')

In [73]:
df

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
6119,BRA,South America,Brazil,2019-12-31,0.0,0.0,NaN,0.0,0.0,NaN,...,14103.452,3.4,177.961,8.11,10.1,17.9,NaN,2.2,75.88,0.759
6120,BRA,South America,Brazil,2020-01-01,0.0,0.0,NaN,0.0,0.0,NaN,...,14103.452,3.4,177.961,8.11,10.1,17.9,NaN,2.2,75.88,0.759
6121,BRA,South America,Brazil,2020-01-02,0.0,0.0,NaN,0.0,0.0,NaN,...,14103.452,3.4,177.961,8.11,10.1,17.9,NaN,2.2,75.88,0.759
6122,BRA,South America,Brazil,2020-01-03,0.0,0.0,NaN,0.0,0.0,NaN,...,14103.452,3.4,177.961,8.11,10.1,17.9,NaN,2.2,75.88,0.759
6123,BRA,South America,Brazil,2020-01-04,0.0,0.0,NaN,0.0,0.0,NaN,...,14103.452,3.4,177.961,8.11,10.1,17.9,NaN,2.2,75.88,0.759
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6391,BRA,South America,Brazil,2020-09-28,4732309.0,14318.0,26811.429,141741.0,335.0,692.286,...,14103.452,3.4,177.961,8.11,10.1,17.9,NaN,2.2,75.88,0.759
6392,BRA,South America,Brazil,2020-09-29,4745464.0,13155.0,26770.857,142058.0,317.0,683.714,...,14103.452,3.4,177.961,8.11,10.1,17.9,NaN,2.2,75.88,0.759
6393,BRA,South America,Brazil,2020-09-30,4777522.0,32058.0,26559.714,142921.0,863.0,687.571,...,14103.452,3.4,177.961,8.11,10.1,17.9,NaN,2.2,75.88,0.759
6394,BRA,South America,Brazil,2020-10-01,4810935.0,33413.0,26578.571,143952.0,1031.0,710.714,...,14103.452,3.4,177.961,8.11,10.1,17.9,NaN,2.2,75.88,0.759
6395,BRA,South America,Brazil,2020-10-02,4847092.0,36157.0,27055.714,144680.0,728.0,696.000,...,14103.452,3.4,177.961,8.11,10.1,17.9,NaN,2.2,75.88,0.759

In [94]:
import datapane
dp.Report(
  dp.Table(df, caption=f'Dataset for {countries}'),
  dp.Blocks(dp.Plot(c1), dp.Plot(c2), columns=2),
  dp.Plot(c3, caption='Total deaths per million')
).publish('covid_report', open=True)

Publishing report and associated data - please wait..
Report successfully published at https://acme.datapane.net/leo/reports/covid_report/

''